# Version number components.
set (SINGERS_MAJOR_VERSION 0)
set (SINGERS_MINOR_VERSION 0)
set (SINGERS_BUILD_VERSION 0)

# Version string
set (SINGERS ${SINGERS_MAJOR_VERSION}.${SINGERS_MINOR_VERSION}.${SINGERS_BUILD_VERSION})
